export const en = {
  common: {
    appName: "My Car",
  },
  database: {
    errorAction: "Try again",
    errorDescription: "The local database could not be prepared. Your data has not been deleted.",
    errorTitle: "The application cannot start",
    loading: "Preparing data",
  },
  firstVehicle: {
    addAction: "Add vehicle",
    description: "Add your vehicle to start keeping its complete history in one place.",
    distanceUnitLabel: "Distance unit",
    genericError: "The vehicle could not be saved. Try again without losing the entered data.",
    initialOdometerHelper:
      "This is the reading when you start the record. Later readings can be added to each entry.",
    initialOdometerLabel: "Odometer when record keeping starts",
    makeLabel: "Make",
    makePlaceholder: "e.g. Toyota",
    manufactureYearLabel: "Manufacture year",
    modelLabel: "Model",
    modelPlaceholder: "e.g. Corolla",
    photoAction: "Add photo",
    photoChangeAction: "Change",
    photoDenied: "Allow gallery access in system settings to select a vehicle photo.",
    photoError:
      "The selected photo could not be prepared. Choose another photo or continue without it.",
    photoLabel: "Vehicle photo",
    photoRemoveAction: "Remove",
    registrationNumberLabel: "Registration number",
    requiredError: "This field is required.",
    invalidNumberError: "Enter a valid non-negative whole number.",
    title: "Add your first vehicle",
    variantLabel: "Variant",
    vinError: "Enter a valid 17-character VIN.",
    vinLabel: "VIN",
    yearError: "Enter a valid manufacture year.",
  },
  orientation: {
    phoneDescription: "The phone layout is currently designed for portrait orientation.",
    tabletDescription: "The tablet layout is currently designed for landscape orientation.",
    title: "Rotate your device",
  },
  route: {
    errorDescription: "The saved vehicle could not be read. Your data has not been deleted.",
    errorTitle: "The vehicle could not be opened",
    loading: "Opening your vehicle",
  },
  storage: {
    errorDescription: "Local files could not be prepared safely. Your data has not been deleted.",
    errorTitle: "Files are unavailable",
    loading: "Preparing local files",
  },
  workspace: {
    historyDescription: "Your vehicle's chronological history will appear here.",
    makeAndModel: "Make + Model",
    mileage: "Mileage",
    noEntries: "No entries",
    photo: "Vehicle photo",
    variant: "Vehicle variant",
  },
} as const;
