export const en = {
  common: {
    appName: "My Car",
  },
  database: {
    errorAction: "Try again",
    errorDescription: "The local database could not be prepared. Your data has not been deleted.",
    errorTitle: "The application cannot start",
    loading: "Preparing data",
  },
  entryForm: {
    cancel: "Cancel",
    costLabel: "Total cost",
    currencyLabel: "Currency",
    discardChanges: "Discard changes",
    discardDescription: "The entered data will not be saved.",
    discardTitle: "Discard this entry?",
    dateLabel: "Event date",
    descriptionLabel: "Description",
    futureError: "The event date and time cannot be in the future.",
    inspectionKindLabel: "Inspection kind",
    inspectionKinds: { diagnostic: "Diagnostic", other: "Other", technical: "Technical" },
    inspectionResultLabel: "Result",
    inspectionResults: {
      conditional: "Conditional",
      failed: "Failed",
      "not-recorded": "Not recorded",
      passed: "Passed",
    },
    invalidCostError: "Enter a valid non-negative amount with up to two decimal places.",
    invalidOdometerError: "Enter a valid non-negative whole number.",
    itemLabel: "Replaced item",
    keepEditing: "Keep editing",
    manufacturerLabel: "Manufacturer",
    notesLabel: "Notes",
    odometerHelper: "A higher reading will update the vehicle's current mileage.",
    odometerLabel: "Current odometer",
    partNumberLabel: "Part number",
    requiredError: "This field is required.",
    save: "Save",
    saveError: "The entry could not be saved. Your changes remain in the form.",
    serviceProviderLabel: "Workshop or service provider",
    subjectLabel: "Repair subject",
    timeLabel: "Time (UTC)",
    title: { inspection: "Add inspection", repair: "Add repair", replacement: "Add replacement" },
  },
  entryDetail: {
    back: "Back to history",
    cost: "Cost",
    dateTime: "Date and time",
    delete: "Delete entry",
    deleteDescription: "This operation cannot be undone.",
    deleteError: "The entry could not be deleted. Try again.",
    deleteTitle: "Delete {{entry}}?",
    description: "Description",
    edit: "Edit",
    inspectionKind: "Inspection kind",
    inspectionResult: "Result",
    manufacturer: "Manufacturer",
    notes: "Notes",
    odometer: "Odometer",
    partNumber: "Part number",
    serviceProvider: "Workshop or service provider",
  },
  entrySelection: {
    cancel: "Cancel",
    description: "Choose what happened. The entry type cannot be changed after saving.",
    inspectionDescription: "Mandatory check, diagnostics, or another inspection.",
    repairDescription: "Removal of a fault or damage.",
    replacementDescription: "A part, fluid, or consumable.",
    title: "Choose entry type",
  },
  firstVehicle: {
    addAction: "Add vehicle",
    description: "Add your vehicle to start keeping its complete history in one place.",
    distanceUnitLabel: "Distance unit",
    genericError: "The vehicle could not be saved. Try again without losing the entered data.",
    initialOdometerHelper:
      "This is the reading when you start the record. Later readings can be added to each entry.",
    initialOdometerLabel: "Odometer when record keeping starts",
    makeLabel: "Make",
    makePlaceholder: "e.g. Toyota",
    manufactureYearLabel: "Manufacture year",
    modelLabel: "Model",
    modelPlaceholder: "e.g. Corolla",
    photoAction: "Add photo",
    photoChangeAction: "Change",
    photoDenied: "Allow gallery access in system settings to select a vehicle photo.",
    photoError:
      "The selected photo could not be prepared. Choose another photo or continue without it.",
    photoLabel: "Vehicle photo",
    photoRemoveAction: "Remove",
    registrationNumberLabel: "Registration number",
    requiredError: "This field is required.",
    invalidNumberError: "Enter a valid non-negative whole number.",
    title: "Add your first vehicle",
    variantLabel: "Variant",
    vinError: "Enter a valid 17-character VIN.",
    vinLabel: "VIN",
    yearError: "Enter a valid manufacture year.",
  },
  orientation: {
    phoneDescription: "The phone layout is currently designed for portrait orientation.",
    tabletDescription: "The tablet layout is currently designed for landscape orientation.",
    title: "Rotate your device",
  },
  route: {
    errorDescription: "The saved vehicle could not be read. Your data has not been deleted.",
    errorTitle: "The vehicle could not be opened",
    loading: "Opening your vehicle",
  },
  storage: {
    errorDescription: "Local files could not be prepared safely. Your data has not been deleted.",
    errorTitle: "Files are unavailable",
    loading: "Preparing local files",
  },
  vehicleEdit: {
    cancel: "Cancel",
    error: "The vehicle could not be updated. Your changes remain in the form.",
    save: "Save vehicle",
    title: "Edit vehicle",
  },
  workspace: {
    addEntry: "Add entry",
    addFirstEntry: "Add first entry",
    editVehicle: "Edit vehicle",
    entryType: {
      inspection: "Inspection",
      repair: "Repair",
      replacement: "Replacement",
    },
    errorDescription: "The vehicle history could not be read. Your data has not been deleted.",
    errorTitle: "History is unavailable",
    historyDescription: "Your vehicle's chronological history will appear here.",
    historyTitle: "History",
    loading: "Loading vehicle history",
    makeAndModel: "Make + Model",
    mileage: "Mileage",
    noMileage: "No reading",
    noEntries: "No entries",
    photo: "Vehicle photo",
    photoDescription: "Photo of {{make}} {{model}}",
    variant: "Vehicle variant",
  },
} as const;
