export const en = {
  common: {
    appName: "My Car",
  },
  database: {
    errorAction: "Try again",
    errorDescription: "The local database could not be prepared. Your data has not been deleted.",
    errorTitle: "The application cannot start",
    loading: "Preparing data",
  },
  documents: {
    add: "Add document",
    addTitle: "Add document or invoice",
    amount: "Amount",
    back: "Back to history",
    cancel: "Cancel",
    chooseFile: "Choose file",
    currency: "Currency",
    date: "Document date",
    dateHelper: "Optional date in YYYY-MM-DD format.",
    delete: "Delete document",
    deleteDescription: "The managed copy and its metadata will be permanently deleted.",
    deleteError: "The document could not be deleted. Try again.",
    deleteTitle: "Delete {{name}}?",
    discard: "Discard changes",
    discardDescription: "The entered metadata will not be saved.",
    discardTitle: "Discard this document?",
    document: "Document",
    duplicateError:
      "This file is already stored. Open the existing document to change its relation.",
    edit: "Edit metadata",
    editTitle: "Edit document metadata",
    empty: "No documents",
    emptyDescription: "Add an invoice, receipt, or other file related to this vehicle.",
    export: "Export document",
    file: "File",
    fileHelper: "Supported formats: PDF, JPEG, and PNG. Maximum size: 20 MB.",
    fileMissing: "The managed file is unavailable.",
    fileRequired: "Choose a file before saving.",
    fileTooLarge: "The file exceeds the 20 MB limit.",
    invalidAmount: "Enter a valid non-negative amount using the currency's decimal precision.",
    keepEditing: "Keep editing",
    name: "Name",
    notes: "Notes",
    openPdf: "Open or export PDF",
    pickError: "The system file picker could not be opened.",
    relation: "Related to",
    replace: "Replace file",
    replaceError: "The document could not be replaced. The previous file remains available.",
    required: "This field is required.",
    save: "Save document",
    saveError: "The document could not be saved. Your changes remain in the form.",
    shareError: "The document could not be opened or exported.",
    shareUnavailable: "Document sharing is unavailable on this device.",
    title: "Documents and invoices",
    unsupportedFile: "Choose a PDF, JPEG, or PNG file.",
    vehicleOnly: "Vehicle only",
  },
  entryForm: {
    cancel: "Cancel",
    costLabel: "Total cost",
    currencyLabel: "Currency",
    discardChanges: "Discard changes",
    discardDescription: "The entered data will not be saved.",
    discardTitle: "Discard this entry?",
    dateLabel: "Event date",
    descriptionLabel: "Description",
    editTitle: {
      inspection: "Edit inspection",
      repair: "Edit repair",
      replacement: "Edit replacement",
    },
    futureError: "The event date and time cannot be in the future.",
    inspectionKindLabel: "Inspection kind",
    inspectionKinds: { diagnostic: "Diagnostic", other: "Other", technical: "Technical" },
    inspectionResultLabel: "Result",
    inspectionResults: {
      conditional: "Conditional",
      failed: "Failed",
      "not-recorded": "Not recorded",
      passed: "Passed",
    },
    invalidCostError: "Enter a valid non-negative amount with up to two decimal places.",
    invalidOdometerError: "Enter a valid non-negative whole number.",
    itemLabel: "Replaced item",
    keepEditing: "Keep editing",
    manufacturerLabel: "Manufacturer",
    notesLabel: "Notes",
    odometerHelper: "A higher reading will update the vehicle's current mileage.",
    odometerLabel: "Current odometer",
    partNumberLabel: "Part number",
    requiredError: "This field is required.",
    save: "Save",
    saveError: "The entry could not be saved. Your changes remain in the form.",
    serviceProviderLabel: "Workshop or service provider",
    subjectLabel: "Repair subject",
    timeLabel: "Time (UTC)",
    title: { inspection: "Add inspection", repair: "Add repair", replacement: "Add replacement" },
  },
  entryDetail: {
    back: "Back to history",
    cost: "Cost",
    dateTime: "Date and time",
    delete: "Delete entry",
    deleteDescription: "This operation cannot be undone.",
    deleteError: "The entry could not be deleted. Try again.",
    deleteTitle: "Delete {{entry}}?",
    description: "Description",
    edit: "Edit",
    inspectionKind: "Inspection kind",
    inspectionResult: "Result",
    manufacturer: "Manufacturer",
    notes: "Notes",
    odometer: "Odometer",
    partNumber: "Part number",
    serviceProvider: "Workshop or service provider",
  },
  entrySelection: {
    cancel: "Cancel",
    description: "Choose what happened. The entry type cannot be changed after saving.",
    inspectionDescription: "Mandatory check, diagnostics, or another inspection.",
    repairDescription: "Removal of a fault or damage.",
    replacementDescription: "A part, fluid, or consumable.",
    title: "Choose entry type",
  },
  firstVehicle: {
    addAction: "Add vehicle",
    description: "Add your vehicle to start keeping its complete history in one place.",
    distanceUnitLabel: "Distance unit",
    fuelConsumptionUnitLabel: "Fuel consumption unit",
    fuelSettingsLabel: "Fuel settings",
    fuelTankCapacityError: "Enter a valid fuel tank capacity greater than zero.",
    fuelTankCapacityLabel: "Fuel tank capacity",
    fuelVolumeUnitLabel: "Fuel volume unit",
    genericError: "The vehicle could not be saved. Try again without losing the entered data.",
    initialOdometerHelper:
      "This is the reading when you start the record. Later readings can be added to each entry.",
    initialOdometerLabel: "Odometer when record keeping starts",
    makeLabel: "Make",
    makePlaceholder: "e.g. Toyota",
    manufactureYearLabel: "Manufacture year",
    modelLabel: "Model",
    modelPlaceholder: "e.g. Corolla",
    photoAction: "Add photo",
    photoChangeAction: "Change",
    photoDenied: "Allow gallery access in system settings to select a vehicle photo.",
    photoError:
      "The selected photo could not be prepared. Choose another photo or continue without it.",
    photoLabel: "Vehicle photo",
    photoRemoveAction: "Remove",
    registrationNumberLabel: "Registration number",
    requiredError: "This field is required.",
    invalidNumberError: "Enter a valid non-negative whole number.",
    title: "Add your first vehicle",
    variantLabel: "Variant",
    vinError: "Enter a valid 17-character VIN.",
    vinLabel: "VIN",
    yearError: "Enter a valid manufacture year.",
  },
  orientation: {
    phoneDescription: "The phone layout is currently designed for portrait orientation.",
    tabletDescription: "The tablet layout is currently designed for landscape orientation.",
    title: "Rotate your device",
  },
  refuelling: {
    add: "Add refuelling",
    addTitle: "Add refuelling",
    averageConsumption: "Average consumption",
    awaitingConsumption:
      "Add two full refuellings with odometer readings to calculate consumption.",
    back: "Back to vehicle history",
    backToFuel: "Back to fuel history",
    basedOn_one: "Based on {{count}} refuelling record marked below.",
    basedOn_other: "Based on {{count}} refuelling records marked below.",
    cancel: "Cancel",
    configurationRequired:
      "Complete the fuel tank capacity and unit preferences before adding a refuelling.",
    configureVehicle: "Complete vehicle fuel settings",
    currencyLabel: "Currency",
    dateLabel: "Refuelling date",
    dateTime: "Date and time",
    delete: "Delete refuelling",
    deleteDescription: "{{date}} — {{quantity}}{{odometer}}. This operation cannot be undone.",
    deleteError: "The refuelling could not be deleted. Try again.",
    deleteTitle: "Delete this refuelling?",
    discard: "Discard changes",
    discardDescription: "The entered refuelling data will not be saved.",
    discardTitle: "Discard this refuelling?",
    edit: "Edit",
    editTitle: "Edit refuelling",
    empty: "No refuellings",
    emptyDescription: "Add a full or partial refuelling to start the fuel history.",
    enteredAs: "Price entered as",
    fillKind: { full: "Full tank", partial: "Partial fill" },
    fillKindLabel: "Fill type",
    futureError: "The refuelling date and time cannot be in the future.",
    includedInAverage: "Included in the average",
    intervalReason: {
      "decreasing-odometer": "The odometer readings decrease within an interval.",
      "missing-end-odometer": "The ending full refuelling needs an odometer reading.",
      "missing-start-odometer": "The starting full refuelling needs an odometer reading.",
      "mixed-vehicles": "The interval contains records from different vehicles.",
      "non-positive-distance": "The ending odometer must be higher than the starting reading.",
      "unsafe-total": "The interval values are too large to calculate safely.",
    },
    invalidCurrency: "Enter a valid three-letter currency code.",
    invalidOdometer: "Enter a valid non-negative whole number.",
    invalidPrice: "Enter a valid price. A unit price may contain at most three decimal places.",
    invalidQuantity: "Enter a fuel quantity greater than zero.",
    keepEditing: "Keep editing",
    odometerHelper: "Optional. A higher reading will update the vehicle's current mileage.",
    odometerLabel: "Current odometer",
    priceMode: { perVolumeUnit: "Price per volume unit", total: "Total amount" },
    priceModeLabel: "Price entry mode",
    priceOptional: "Optional. Leave empty if the price is unknown.",
    quantityLabel: "Fuel quantity",
    save: "Save refuelling",
    saveError: "The refuelling could not be saved. Your changes remain in the form.",
    timeLabel: "Time (UTC)",
    title: "Fuel",
    totalPriceLabel: "Total amount",
    unitPriceLabel: "Unit price",
    volumeUnit: {
      imperialGallons: "Imperial gallons",
      litres: "Litres",
      usGallons: "US gallons",
    },
    volumeUnitLabel: "Fuel volume unit",
  },
  route: {
    errorDescription: "The saved vehicle could not be read. Your data has not been deleted.",
    errorTitle: "The vehicle could not be opened",
    loading: "Opening your vehicle",
  },
  storage: {
    errorDescription: "Local files could not be prepared safely. Your data has not been deleted.",
    errorTitle: "Files are unavailable",
    loading: "Preparing local files",
  },
  vehicleEdit: {
    cancel: "Cancel",
    error: "The vehicle could not be updated. Your changes remain in the form.",
    save: "Save vehicle",
    title: "Edit vehicle",
  },
  workspace: {
    addEntry: "Add entry",
    addFirstEntry: "Add first entry",
    editVehicle: "Edit vehicle",
    entryType: {
      inspection: "Inspection",
      repair: "Repair",
      replacement: "Replacement",
    },
    errorDescription: "The vehicle history could not be read. Your data has not been deleted.",
    errorTitle: "History is unavailable",
    historyDescription: "Your vehicle's chronological history will appear here.",
    historyTitle: "History",
    loading: "Loading vehicle history",
    makeAndModel: "Make + Model",
    mileage: "Mileage",
    noMileage: "No reading",
    noEntries: "No entries",
    photo: "Vehicle photo",
    photoDescription: "Photo of {{make}} {{model}}",
    variant: "Vehicle variant",
  },
} as const;
