export const pl = {
  common: {
    appName: "Moje Auto",
  },
  database: {
    errorAction: "Spróbuj ponownie",
    errorDescription:
      "Nie udało się przygotować lokalnej bazy danych. Twoje dane nie zostały usunięte.",
    errorTitle: "Nie można uruchomić aplikacji",
    loading: "Przygotowywanie danych",
  },
  entryForm: {
    cancel: "Anuluj",
    costLabel: "Koszt całkowity",
    currencyLabel: "Waluta",
    discardChanges: "Odrzuć zmiany",
    discardDescription: "Wprowadzone dane nie zostaną zapisane.",
    discardTitle: "Odrzucić ten wpis?",
    dateLabel: "Data zdarzenia",
    descriptionLabel: "Opis",
    editTitle: {
      inspection: "Edytuj przegląd",
      repair: "Edytuj naprawę",
      replacement: "Edytuj wymianę",
    },
    futureError: "Data i godzina zdarzenia nie mogą być w przyszłości.",
    inspectionKindLabel: "Rodzaj przeglądu",
    inspectionKinds: { diagnostic: "Diagnostyczny", other: "Inny", technical: "Techniczny" },
    inspectionResultLabel: "Wynik",
    inspectionResults: {
      conditional: "Warunkowy",
      failed: "Niezaliczony",
      "not-recorded": "Nie zapisano",
      passed: "Zaliczony",
    },
    invalidCostError: "Wpisz poprawną nieujemną kwotę z najwyżej dwoma miejscami po przecinku.",
    invalidOdometerError: "Wpisz poprawną nieujemną liczbę całkowitą.",
    itemLabel: "Wymieniony element",
    keepEditing: "Kontynuuj edycję",
    manufacturerLabel: "Producent",
    notesLabel: "Notatki",
    odometerHelper: "Wyższy odczyt zaktualizuje obecny przebieg pojazdu.",
    odometerLabel: "Bieżący licznik",
    partNumberLabel: "Numer części",
    requiredError: "To pole jest wymagane.",
    save: "Zapisz",
    saveError: "Nie udało się zapisać wpisu. Zmiany pozostają w formularzu.",
    serviceProviderLabel: "Warsztat lub usługodawca",
    subjectLabel: "Przedmiot naprawy",
    timeLabel: "Godzina (UTC)",
    title: { inspection: "Dodaj przegląd", repair: "Dodaj naprawę", replacement: "Dodaj wymianę" },
  },
  entryDetail: {
    back: "Wróć do historii",
    cost: "Koszt",
    dateTime: "Data i czas",
    delete: "Usuń wpis",
    deleteDescription: "Tej operacji nie można cofnąć.",
    deleteError: "Nie udało się usunąć wpisu. Spróbuj ponownie.",
    deleteTitle: "Usunąć {{entry}}?",
    description: "Opis",
    edit: "Edytuj",
    inspectionKind: "Rodzaj przeglądu",
    inspectionResult: "Wynik",
    manufacturer: "Producent",
    notes: "Notatki",
    odometer: "Przebieg",
    partNumber: "Numer części",
    serviceProvider: "Warsztat lub usługodawca",
  },
  entrySelection: {
    cancel: "Anuluj",
    description: "Wybierz, co się wydarzyło. Po zapisie nie można zmienić typu wpisu.",
    inspectionDescription: "Obowiązkowe badanie, diagnostyka albo inna kontrola.",
    repairDescription: "Usunięcie usterki albo uszkodzenia.",
    replacementDescription: "Część, płyn albo materiał eksploatacyjny.",
    title: "Wybierz typ wpisu",
  },
  firstVehicle: {
    addAction: "Dodaj pojazd",
    description: "Dodaj pojazd, aby rozpocząć prowadzenie jego pełnej historii w jednym miejscu.",
    distanceUnitLabel: "Jednostka odległości",
    genericError:
      "Nie udało się zapisać pojazdu. Spróbuj ponownie bez utraty wprowadzonych danych.",
    initialOdometerHelper:
      "To odczyt z momentu rozpoczęcia ewidencji. Późniejsze odczyty możesz dodawać do każdego wpisu.",
    initialOdometerLabel: "Stan licznika na moment rozpoczęcia ewidencji",
    makeLabel: "Marka",
    makePlaceholder: "np. Toyota",
    manufactureYearLabel: "Rok produkcji",
    modelLabel: "Model",
    modelPlaceholder: "np. Corolla",
    photoAction: "Dodaj zdjęcie",
    photoChangeAction: "Zmień",
    photoDenied: "Zezwól na dostęp do galerii w ustawieniach systemu, aby wybrać zdjęcie pojazdu.",
    photoError:
      "Nie udało się przygotować wybranego zdjęcia. Wybierz inne albo kontynuuj bez niego.",
    photoLabel: "Zdjęcie pojazdu",
    photoRemoveAction: "Usuń",
    registrationNumberLabel: "Numer rejestracyjny",
    requiredError: "To pole jest wymagane.",
    invalidNumberError: "Wpisz poprawną nieujemną liczbę całkowitą.",
    title: "Dodaj pierwszy pojazd",
    variantLabel: "Wersja",
    vinError: "Wpisz poprawny, 17-znakowy numer VIN.",
    vinLabel: "VIN",
    yearError: "Wpisz poprawny rok produkcji.",
  },
  orientation: {
    phoneDescription: "Widok telefonu jest obecnie przygotowany do pracy w pionie.",
    tabletDescription: "Widok tabletu jest obecnie przygotowany do pracy w poziomie.",
    title: "Obróć urządzenie",
  },
  route: {
    errorDescription: "Nie udało się odczytać zapisanego pojazdu. Twoje dane nie zostały usunięte.",
    errorTitle: "Nie można otworzyć pojazdu",
    loading: "Otwieranie pojazdu",
  },
  storage: {
    errorDescription:
      "Nie udało się bezpiecznie przygotować lokalnych plików. Twoje dane nie zostały usunięte.",
    errorTitle: "Pliki są niedostępne",
    loading: "Przygotowywanie lokalnych plików",
  },
  vehicleEdit: {
    cancel: "Anuluj",
    error: "Nie udało się zaktualizować pojazdu. Zmiany pozostają w formularzu.",
    save: "Zapisz pojazd",
    title: "Edytuj pojazd",
  },
  workspace: {
    addEntry: "Dodaj wpis",
    addFirstEntry: "Dodaj pierwszy wpis",
    editVehicle: "Edytuj pojazd",
    entryType: {
      inspection: "Przegląd",
      repair: "Naprawa",
      replacement: "Wymiana",
    },
    errorDescription: "Nie udało się odczytać historii pojazdu. Twoje dane nie zostały usunięte.",
    errorTitle: "Historia jest niedostępna",
    historyDescription: "W tym miejscu pojawi się chronologiczna historia pojazdu.",
    historyTitle: "Historia",
    loading: "Wczytywanie historii pojazdu",
    makeAndModel: "Marka + Model",
    mileage: "Przebieg",
    noMileage: "Brak odczytu",
    noEntries: "Brak wpisów",
    photo: "Zdjęcie pojazdu",
    photoDescription: "Zdjęcie pojazdu {{make}} {{model}}",
    variant: "Wersja pojazdu",
  },
} as const;
