export const pl = {
  reminders: {
    title: "Przypomnienia",
    kinds: { insurance: "Ubezpieczenie", technicalInspection: "Badanie techniczne" },
    dateLabels: {
      insurance: "Ubezpieczenie ważne do",
      technicalInspection: "Badanie techniczne ważne do",
    },
    status: { upcoming: "Nadchodzący", dueToday: "Dzisiaj", overdue: "Po terminie" },
    offsets: { 7: "7 dni wcześniej", 1: "1 dzień wcześniej", 0: "W dniu terminu" },
    add: "Dodaj termin",
    addKind: "Dodaj termin: {{kind}}",
    edit: "Edytuj",
    editKind: "Edytuj termin: {{kind}}",
    chooseDate: "Wybierz datę",
    confirmDate: "Zatwierdź datę",
    cancelDate: "Anuluj wybór daty",
    dateRequired: "Wybierz poprawną datę.",
    notifyWhen: "Powiadom mnie",
    zoneHelper: "O 09:00 w strefie {{zone}}. Ta strefa nie zmieni się podczas podróży.",
    alertsOff: "Powiadomienia dla tego terminu są wyłączone. Data pozostaje na liście.",
    permissionOnSave:
      "Najpierw zapisz termin. Potem możesz zezwolić na powiadomienia — zgoda jest opcjonalna.",
    save: "Zapisz termin",
    cancel: "Anuluj",
    delete: "Usuń termin",
    back: "Wróć do historii",
    discardTitle: "Odrzucić zmiany?",
    discardDescription: "Niezapisane zmiany terminu zostaną utracone.",
    keepEditing: "Kontynuuj edycję",
    discard: "Odrzuć",
    deleteTitle: "Usunąć termin?",
    deleteDescription: "Termin zostanie usunięty, a jego zaplanowane powiadomienia anulowane.",
    saveError: "Nie udało się zapisać terminu. Zmiany pozostały w formularzu. Spróbuj ponownie.",
    conflictError: "Ten termin już istnieje. Wróć do listy i edytuj istniejący termin.",
    deleteError: "Nie udało się usunąć terminu. Spróbuj ponownie.",
    loading: "Wczytywanie terminów…",
    loadError: "Nie udało się wczytać terminów.",
    retry: "Spróbuj ponownie",
    notificationsTitle: "Powiadomienia",
    permissionUnknown: "Sprawdzanie zgody na powiadomienia…",
    permissionUnavailable: "Nie udało się sprawdzić zgody na powiadomienia.",
    permissionEnabled: "Zgoda na powiadomienia jest włączona.",
    permissionQuiet:
      "Powiadomienia są dostarczane po cichu. Możesz to zmienić w ustawieniach systemowych.",
    permissionDisabled:
      "Powiadomienia są wyłączone. Terminy nadal są zapisane i widoczne na liście.",
    permissionExplanation:
      "Pozwól aplikacji przypominać o ubezpieczeniu i badaniu w wybrane dni o 09:00 w zapamiętanej strefie. Możesz pominąć zgodę i korzystać z terminów bez powiadomień.",
    enableNotifications: "Zezwól na powiadomienia",
    openSettings: "Otwórz ustawienia powiadomień",
    scheduleError:
      "Nie udało się zaktualizować powiadomień. Terminy są bezpieczne. Spróbuj ponownie.",
    deliveryDisclaimer:
      "Ustawienia systemu i oszczędzanie energii mogą opóźnić lub zablokować powiadomienie. Sprawdzaj terminy na tej liście.",
  },
  notifications: {
    channelName: "Przypomnienia o pojeździe",
    insuranceTitle: "Termin ubezpieczenia",
    inspectionTitle: "Termin badania technicznego",
    validUntil: "{{vehicle}} — ważne do {{date}}.",
  },
  common: {
    appName: "Moje Auto",
  },
  database: {
    errorAction: "Spróbuj ponownie",
    errorDescription:
      "Nie udało się przygotować lokalnej bazy danych. Twoje dane nie zostały usunięte.",
    errorTitle: "Nie można uruchomić aplikacji",
    loading: "Przygotowywanie danych",
  },
  documents: {
    add: "Dodaj dokument",
    addTitle: "Dodaj dokument lub fakturę",
    amount: "Kwota",
    back: "Wróć do historii",
    cancel: "Anuluj",
    chooseFile: "Wybierz plik",
    currency: "Waluta",
    date: "Data dokumentu",
    dateHelper: "Opcjonalna data w formacie RRRR-MM-DD.",
    delete: "Usuń dokument",
    deleteDescription: "Zarządzana kopia pliku i jej metadane zostaną trwale usunięte.",
    deleteError: "Nie udało się usunąć dokumentu. Spróbuj ponownie.",
    deleteTitle: "Usunąć {{name}}?",
    discard: "Odrzuć zmiany",
    discardDescription: "Wprowadzone metadane nie zostaną zapisane.",
    discardTitle: "Odrzucić ten dokument?",
    document: "Dokument",
    duplicateError:
      "Ten plik jest już zapisany. Otwórz istniejący dokument, aby zmienić jego powiązanie.",
    edit: "Edytuj metadane",
    editTitle: "Edytuj metadane dokumentu",
    empty: "Brak dokumentów",
    emptyDescription: "Dodaj fakturę, paragon lub inny plik związany z pojazdem.",
    export: "Eksportuj dokument",
    file: "Plik",
    fileHelper: "Obsługiwane formaty: PDF, JPEG i PNG. Maksymalny rozmiar: 20 MB.",
    fileMissing: "Zarządzany plik jest niedostępny.",
    fileRequired: "Wybierz plik przed zapisaniem.",
    fileTooLarge: "Plik przekracza limit 20 MB.",
    invalidAmount: "Wpisz poprawną nieujemną kwotę zgodną z precyzją wybranej waluty.",
    keepEditing: "Kontynuuj edycję",
    name: "Nazwa",
    notes: "Notatki",
    openPdf: "Otwórz lub eksportuj PDF",
    pickError: "Nie udało się otworzyć systemowego selektora plików.",
    relation: "Powiązanie",
    replace: "Zastąp plik",
    replaceError: "Nie udało się zastąpić dokumentu. Poprzedni plik pozostaje dostępny.",
    required: "To pole jest wymagane.",
    save: "Zapisz dokument",
    saveError: "Nie udało się zapisać dokumentu. Zmiany pozostają w formularzu.",
    shareError: "Nie udało się otworzyć lub wyeksportować dokumentu.",
    shareUnavailable: "Udostępnianie dokumentów jest niedostępne na tym urządzeniu.",
    title: "Dokumenty i faktury",
    unsupportedFile: "Wybierz plik PDF, JPEG lub PNG.",
    vehicleOnly: "Tylko pojazd",
  },
  entryForm: {
    cancel: "Anuluj",
    costLabel: "Koszt całkowity",
    currencyLabel: "Waluta",
    discardChanges: "Odrzuć zmiany",
    discardDescription: "Wprowadzone dane nie zostaną zapisane.",
    discardTitle: "Odrzucić ten wpis?",
    dateLabel: "Data zdarzenia",
    descriptionLabel: "Opis",
    editTitle: {
      inspection: "Edytuj przegląd",
      repair: "Edytuj naprawę",
      replacement: "Edytuj wymianę",
    },
    futureError: "Data i godzina zdarzenia nie mogą być w przyszłości.",
    inspectionKindLabel: "Rodzaj przeglądu",
    inspectionKinds: { diagnostic: "Diagnostyczny", other: "Inny", technical: "Techniczny" },
    inspectionResultLabel: "Wynik",
    inspectionResults: {
      conditional: "Warunkowy",
      failed: "Niezaliczony",
      "not-recorded": "Nie zapisano",
      passed: "Zaliczony",
    },
    invalidCostError: "Wpisz poprawną nieujemną kwotę z najwyżej dwoma miejscami po przecinku.",
    invalidOdometerError: "Wpisz poprawną nieujemną liczbę całkowitą.",
    itemLabel: "Wymieniony element",
    keepEditing: "Kontynuuj edycję",
    manufacturerLabel: "Producent",
    notesLabel: "Notatki",
    odometerHelper: "Wyższy odczyt zaktualizuje obecny przebieg pojazdu.",
    odometerLabel: "Bieżący licznik",
    partNumberLabel: "Numer części",
    requiredError: "To pole jest wymagane.",
    save: "Zapisz",
    saveError: "Nie udało się zapisać wpisu. Zmiany pozostają w formularzu.",
    serviceProviderLabel: "Warsztat lub usługodawca",
    subjectLabel: "Przedmiot naprawy",
    timeLabel: "Godzina",
    title: { inspection: "Dodaj przegląd", repair: "Dodaj naprawę", replacement: "Dodaj wymianę" },
  },
  entryDetail: {
    back: "Wróć do historii",
    cost: "Koszt",
    dateTime: "Data i czas",
    delete: "Usuń wpis",
    deleteDescription: "Tej operacji nie można cofnąć.",
    deleteError: "Nie udało się usunąć wpisu. Spróbuj ponownie.",
    deleteTitle: "Usunąć {{entry}}?",
    description: "Opis",
    edit: "Edytuj",
    inspectionKind: "Rodzaj przeglądu",
    inspectionResult: "Wynik",
    manufacturer: "Producent",
    notes: "Notatki",
    odometer: "Przebieg",
    partNumber: "Numer części",
    serviceProvider: "Warsztat lub usługodawca",
  },
  entrySelection: {
    cancel: "Anuluj",
    description: "Wybierz, co się wydarzyło. Po zapisie nie można zmienić typu wpisu.",
    inspectionDescription: "Obowiązkowe badanie, diagnostyka albo inna kontrola.",
    repairDescription: "Usunięcie usterki albo uszkodzenia.",
    replacementDescription: "Część, płyn albo materiał eksploatacyjny.",
    title: "Wybierz typ wpisu",
  },
  firstVehicle: {
    addAction: "Dodaj pojazd",
    description: "Dodaj pojazd, aby rozpocząć prowadzenie jego pełnej historii w jednym miejscu.",
    distanceUnitLabel: "Jednostka odległości",
    fuelConsumptionUnitLabel: "Jednostka zużycia paliwa",
    fuelSettingsLabel: "Ustawienia paliwa",
    fuelTankCapacityError: "Wpisz całkowitą pojemność zbiornika paliwa większą od zera.",
    fuelTankCapacityLabel: "Pojemność zbiornika paliwa",
    fuelVolumeUnitLabel: "Jednostka objętości paliwa",
    genericError:
      "Nie udało się zapisać pojazdu. Spróbuj ponownie bez utraty wprowadzonych danych.",
    initialOdometerHelper:
      "To odczyt z momentu rozpoczęcia ewidencji. Późniejsze odczyty możesz dodawać do każdego wpisu.",
    initialOdometerLabel: "Stan licznika na moment rozpoczęcia ewidencji",
    makeLabel: "Marka",
    makePlaceholder: "np. Toyota",
    manufactureYearLabel: "Rok produkcji",
    modelLabel: "Model",
    modelPlaceholder: "np. Corolla",
    photoAction: "Dodaj zdjęcie",
    photoChangeAction: "Zmień",
    photoDenied: "Zezwól na dostęp do galerii w ustawieniach systemu, aby wybrać zdjęcie pojazdu.",
    photoError:
      "Nie udało się przygotować wybranego zdjęcia. Wybierz inne albo kontynuuj bez niego.",
    photoLabel: "Zdjęcie pojazdu",
    photoRemoveAction: "Usuń",
    registrationNumberLabel: "Numer rejestracyjny",
    requiredError: "To pole jest wymagane.",
    invalidNumberError: "Wpisz poprawną nieujemną liczbę całkowitą.",
    title: "Dodaj pierwszy pojazd",
    variantLabel: "Wersja",
    vinError: "Wpisz poprawny, 17-znakowy numer VIN.",
    vinLabel: "VIN",
    yearError: "Wpisz poprawny rok produkcji.",
  },
  orientation: {
    phoneDescription: "Widok telefonu jest obecnie przygotowany do pracy w pionie.",
    tabletDescription: "Widok tabletu jest obecnie przygotowany do pracy w poziomie.",
    title: "Obróć urządzenie",
  },
  refuelling: {
    add: "Dodaj tankowanie",
    addTitle: "Dodaj tankowanie",
    averageConsumption: "Średnie zużycie",
    awaitingConsumption: "Dodaj dwa pełne tankowania z odczytami licznika, aby obliczyć zużycie.",
    back: "Wróć do historii pojazdu",
    backToFuel: "Wróć do historii tankowań",
    basedOn: "Liczba tankowań uwzględnionych w średniej: {{recordCount}}.",
    cancel: "Anuluj",
    configurationRequired:
      "Uzupełnij pojemność zbiornika i preferencje jednostek przed dodaniem tankowania.",
    configureVehicle: "Uzupełnij ustawienia paliwa pojazdu",
    currencyLabel: "Waluta",
    dateLabel: "Data tankowania",
    dateTime: "Data i godzina",
    delete: "Usuń tankowanie",
    deleteDescription: "{{date}} — {{quantity}}{{odometer}}. Tej operacji nie można cofnąć.",
    deleteError: "Nie udało się usunąć tankowania. Spróbuj ponownie.",
    deleteTitle: "Usunąć to tankowanie?",
    discard: "Odrzuć zmiany",
    discardDescription: "Wprowadzone dane tankowania nie zostaną zapisane.",
    discardTitle: "Odrzucić to tankowanie?",
    edit: "Edytuj",
    editTitle: "Edytuj tankowanie",
    empty: "Brak tankowań",
    emptyDescription: "Dodaj pełne lub częściowe tankowanie, aby rozpocząć historię paliwa.",
    enteredAs: "Sposób podania ceny",
    fillKind: { full: "Do pełna", partial: "Częściowe" },
    fillKindLabel: "Rodzaj tankowania",
    futureError: "Data i godzina tankowania nie mogą być w przyszłości.",
    includedInAverage: "Uwzględnione w średniej",
    intervalReason: {
      "decreasing-odometer": "Odczyty licznika maleją wewnątrz przedziału.",
      "missing-end-odometer": "Końcowe pełne tankowanie wymaga odczytu licznika.",
      "missing-start-odometer": "Początkowe pełne tankowanie wymaga odczytu licznika.",
      "mixed-vehicles": "Przedział zawiera rekordy różnych pojazdów.",
      "non-positive-distance": "Końcowy licznik musi być wyższy od początkowego.",
      "unsafe-total": "Wartości przedziału są zbyt duże, aby bezpiecznie je obliczyć.",
    },
    invalidCurrency: "Wpisz poprawny trzyliterowy kod waluty.",
    invalidOdometer: "Wpisz poprawną nieujemną liczbę całkowitą.",
    invalidPrice:
      "Wpisz poprawną cenę. Cena jednostkowa może mieć najwyżej trzy miejsca po przecinku.",
    invalidQuantity:
      "Wpisz ilość paliwa większą od zera, używając maksymalnie dwóch miejsc po przecinku.",
    keepEditing: "Kontynuuj edycję",
    odometerHelper: "Pole opcjonalne. Wyższy odczyt zaktualizuje obecny przebieg pojazdu.",
    odometerLabel: "Bieżący licznik",
    priceMode: { perVolumeUnit: "Cena za jednostkę objętości", total: "Kwota całkowita" },
    priceModeLabel: "Sposób podania ceny",
    priceOptional: "Pole opcjonalne. Pozostaw puste, jeśli cena jest nieznana.",
    quantityLabel: "Ilość paliwa",
    save: "Zapisz tankowanie",
    saveError: "Nie udało się zapisać tankowania. Zmiany pozostają w formularzu.",
    timeLabel: "Godzina",
    title: "Paliwo",
    totalPriceLabel: "Kwota całkowita",
    unitPriceLabel: "Cena jednostkowa",
    volumeUnit: {
      imperialGallons: "Galony imperialne",
      litres: "Litry",
      usGallons: "Galony amerykańskie",
    },
    volumeUnitLabel: "Jednostka objętości paliwa",
  },
  route: {
    errorDescription: "Nie udało się odczytać zapisanego pojazdu. Twoje dane nie zostały usunięte.",
    errorTitle: "Nie można otworzyć pojazdu",
    loading: "Otwieranie pojazdu",
  },
  storage: {
    errorDescription:
      "Nie udało się bezpiecznie przygotować lokalnych plików. Twoje dane nie zostały usunięte.",
    errorTitle: "Pliki są niedostępne",
    loading: "Przygotowywanie lokalnych plików",
  },
  vehicleEdit: {
    cancel: "Anuluj",
    error: "Nie udało się zaktualizować pojazdu. Zmiany pozostają w formularzu.",
    save: "Zapisz pojazd",
    title: "Edytuj pojazd",
  },
  workspace: {
    addEntry: "Dodaj wpis",
    addFirstEntry: "Dodaj pierwszy wpis",
    editVehicle: "Edytuj pojazd",
    entryType: {
      inspection: "Przegląd",
      repair: "Naprawa",
      replacement: "Wymiana",
    },
    errorDescription: "Nie udało się odczytać historii pojazdu. Twoje dane nie zostały usunięte.",
    errorTitle: "Historia jest niedostępna",
    historyDescription: "W tym miejscu pojawi się chronologiczna historia pojazdu.",
    historyTitle: "Historia",
    loading: "Wczytywanie historii pojazdu",
    makeAndModel: "Marka + Model",
    mileage: "Przebieg",
    noMileage: "Brak odczytu",
    noEntries: "Brak wpisów",
    photo: "Zdjęcie pojazdu",
    photoDescription: "Zdjęcie pojazdu {{make}} {{model}}",
    variant: "Wersja pojazdu",
  },
} as const;
