import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { createRequire } from "node:module";
import { createHash } from "node:crypto";

const mobile = resolve(import.meta.dirname, "../apps/mobile");
const env = {
  ...process.env,
  RCT_SPM_AUTOLINKING_CONFIG_COMMAND: JSON.stringify([
    "nub",
    "exec",
    "--node",
    "expo-modules-autolinking",
    "react-native-config",
    "--json",
    "--platform",
    "ios",
  ]),
};
function run(args) {
  const result = spawnSync("nub", args, { cwd: mobile, env, stdio: "inherit" });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}

const nativeConfigStamp = resolve(mobile, "ios/.moje-auto-native-config");
const configHash = createHash("sha256").update(process.env.MOJE_AUTO_NATIVE_QA ?? "0");
for (const path of [
  "app.json",
  "app.config.js",
  ...readdirSync(resolve(mobile, "plugins")).map((name) => `plugins/${name}`),
]) {
  configHash.update(path).update(readFileSync(resolve(mobile, path)));
}
const nativeConfig = configHash.digest("hex");
const prebuild =
  !existsSync(nativeConfigStamp) || readFileSync(nativeConfigStamp, "utf8") !== nativeConfig;
if (prebuild || !existsSync(resolve(mobile, "ios/MojeAuto.xcodeproj"))) {
  run(["exec", "sfw", "nub", "exec", "expo", "prebuild", "--platform", "ios", "--no-install"]);
}
const installed = existsSync(resolve(mobile, "ios/MojeAuto.xcodeproj/.spm-injected.json"));
run([
  "exec",
  "react-native",
  "spm",
  installed ? "update" : "add",
  ...(!installed || prebuild ? ["--deintegrate"] : []),
  "--yes",
]);
run(["--node", resolve(import.meta.dirname, "wire-expo-spm.mjs")]);

// SDK 58's automatic sync would discard the consumption fixes before graph resolution.
// Keep both Xcode entry points deterministic and require an explicit NUB preparation.
const require = createRequire(resolve(mobile, "package.json"));
const projectPath = resolve(mobile, "ios/MojeAuto.xcodeproj/project.pbxproj");
const project = require("xcode").project(projectPath);
project.parseSync();
const generated = resolve(mobile, "ios/build/generated/autolinking");
const jsi = resolve(generated, "expo/expo-source/expo-modules-jsi");
const screens = resolve(mobile, "../../node_modules/react-native-screens");
const screenIncludes = [
  ...new Set(
    [
      ...readFileSync(resolve(screens, "Package.swift"), "utf8").matchAll(
        /\.headerSearchPath\("([^"]+)"\)/g,
      ),
    ].map((match) => resolve(screens, match[1])),
  ),
];
const swiftFlags = [
  "$(inherited)",
  "-F",
  resolve(generated, "expo/compile-interfaces"),
  "-cxx-interoperability-mode=default",
  "-Xfrontend",
  "-import-module",
  "-Xfrontend",
  "Foundation",
  "-Xfrontend",
  "-import-module",
  "-Xfrontend",
  "UIKit",
  "-Xfrontend",
  "-import-module",
  "-Xfrontend",
  "React_RCTAppDelegate",
  "-Xcc",
  "-std=c++20",
  "-Xcc",
  "-fapinotes",
  "-Xcc",
  `-fmodule-map-file=${jsi}/jsi.modulemap`,
  "-Xcc",
  "-iapinotes-modules",
  "-Xcc",
  jsi,
  ...screenIncludes.flatMap((path) => ["-Xcc", `-I${path}`]),
];
for (const configuration of Object.values(project.pbxXCBuildConfigurationSection())) {
  if (typeof configuration === "object" && configuration.buildSettings?.SWIFT_VERSION) {
    configuration.buildSettings.OTHER_SWIFT_FLAGS = swiftFlags.map((flag) => JSON.stringify(flag));
    configuration.buildSettings.SWIFT_VERSION = "5.0";
    // The Expo template's empty bridging header creates a second import context.
    delete configuration.buildSettings.SWIFT_OBJC_BRIDGING_HEADER;
  }
}
const nubPath = spawnSync("which", ["nub"], { encoding: "utf8" }).stdout.trim();
if (!nubPath) throw new Error("NUB executable was not found");
const command = `set -e\ncd "$SRCROOT/.."\n${JSON.stringify(nubPath)} --node ../../scripts/check-ios-spm.mjs\n`;
for (const phase of Object.values(project.hash.project.objects.PBXShellScriptBuildPhase)) {
  if (typeof phase === "object" && phase.name === '"Sync SPM Autolinking"') {
    phase.shellScript = JSON.stringify(command);
  }
}
writeFileSync(projectPath, project.writeSync());
const schemePath = resolve(
  mobile,
  "ios/MojeAuto.xcodeproj/xcshareddata/xcschemes/MojeAuto.xcscheme",
);
const xmlCommand = command.replaceAll("&", "&amp;").replaceAll('"', "&quot;");
writeFileSync(
  schemePath,
  readFileSync(schemePath, "utf8").replace(
    /(title = "Sync SPM Autolinking"\s+scriptText = ")[\s\S]*?("\s*>)/,
    `$1${xmlCommand}$2`,
  ),
);
writeFileSync(
  resolve(mobile, "ios/.xcode.env"),
  `# Generated by NUB SwiftPM preparation.\nexport NODE_BINARY=${JSON.stringify(process.execPath)}\nexport RCT_SPM_AUTOLINKING_CONFIG_COMMAND='${env.RCT_SPM_AUTOLINKING_CONFIG_COMMAND}'\n`,
);
run(["--node", resolve(import.meta.dirname, "check-ios-spm.mjs"), "--record"]);
writeFileSync(nativeConfigStamp, nativeConfig);
